name: Build and Test

on:
  push:
    paths:
      - "**/Cargo.toml"
      - "**/Cargo.lock"
    branches: [ "master" ]
  pull_request:
    paths:
      - "**/Cargo.toml"
      - "**/Cargo.lock"
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install cargo-deny
      run: cargo install --locked cargo-deny
    - name: Initialize cargo-deny
      run: cargo deny init
    - name: Check (cargo-deny)
      run: cargo deny check
